
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\xdc;)\x0c\x98(\x1c;\xfe\xecQ\xa8\xd8\x95c\xc0'

_lr_action_items = {'DIVIDE':([2,3,5,7,13,14,15,16,17,18,],[-9,-10,10,-11,-5,-11,10,-6,10,10,]),'NAME':([0,8,9,10,11,12,],[7,14,14,14,14,14,]),'INT':([0,8,9,10,11,12,],[2,2,2,2,2,2,]),'FLOAT':([0,8,9,10,11,12,],[3,3,3,3,3,3,]),'EQUALS':([7,],[12,]),'PLUS':([2,3,5,7,13,14,15,16,17,18,],[-9,-10,9,-11,-5,-11,-7,-6,-8,9,]),'MULTIPLY':([2,3,5,7,13,14,15,16,17,18,],[-9,-10,8,-11,-5,-11,8,-6,8,8,]),'MINUS':([2,3,5,7,13,14,15,16,17,18,],[-9,-10,11,-11,-5,-11,-7,-6,-8,11,]),'$end':([0,1,2,3,4,5,6,7,13,14,15,16,17,18,],[-12,-2,-9,-10,0,-1,-3,-11,-5,-11,-7,-6,-8,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[4,]),'expression':([0,8,9,10,11,12,],[5,13,15,16,17,18,]),'var_assign':([0,],[1,]),'empty':([0,],[6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('calc',1,'p_calc','C:/Users/hp/Desktop/lex-prog/cal.py',56),
  ('calc',1,'p_calc','C:/Users/hp/Desktop/lex-prog/cal.py',57),
  ('calc',1,'p_calc','C:/Users/hp/Desktop/lex-prog/cal.py',58),
  ('var_assign',3,'p_var_assign','C:/Users/hp/Desktop/lex-prog/cal.py',64),
  ('expression',3,'p_expression','C:/Users/hp/Desktop/lex-prog/cal.py',70),
  ('expression',3,'p_expression','C:/Users/hp/Desktop/lex-prog/cal.py',71),
  ('expression',3,'p_expression','C:/Users/hp/Desktop/lex-prog/cal.py',72),
  ('expression',3,'p_expression','C:/Users/hp/Desktop/lex-prog/cal.py',73),
  ('expression',1,'p_expression_int_float','C:/Users/hp/Desktop/lex-prog/cal.py',79),
  ('expression',1,'p_expression_int_float','C:/Users/hp/Desktop/lex-prog/cal.py',80),
  ('expression',1,'p_expression_var','C:/Users/hp/Desktop/lex-prog/cal.py',87),
  ('empty',0,'p_empty','C:/Users/hp/Desktop/lex-prog/cal.py',97),
]
